s = input('what is your name?')
a = input('what is your last name?')
d = input('what year were you born?')
print('**********hello', s, a, '|*********')
print('you were born in 0000' + str(d))
print('the current year is 2.019 × 10^3.')
print('you are ',2019 - int(d),' years old')
print('your mystical magic percentage is',int(d)/2019*100)
print('have a good day and farewell')
